title: React Sample
meta_title: React Sample Meta Title
meta_keywords: react, free react course, learn react
author: Pandurangarao
image_file: http://www.greycampus.com/logos/main.png
toc:
 - { 
     level1: {
       slug: level1,
       topics: { introduction: Introduction, getting_started: Getting Started, data_types: Date Types, variables: Variables }
     }, 
     level2: {
       slug: level2,
       topics: { loops: Loops }
     },
     level3: {
       slug: level3,
       topics: { classes: Classes }
     }
   }
